
package main

import (
	"fmt"
	"index/suffixarray"
)

func main() {
	idx := suffixarray.New([]byte(`TTAGAAGAGATCTGCCGGGACCAGGGCCCTTAGTATTTACGGGAGTAACGAACGCCGGGCCCAAGTTCGTTTGAAAACTAGCTCGTTGTTATGAGCACCCGTAAAGCTAGCTGCATCAATATACAAAAATCGGCGTGTTGATGCGGAATGCAGAGGACTCTTTCTGGCTATAACTTGATGTAAGCCGGACACACCTAGAGCCGTTTGGGAGATGTATATACGCCGTTGGACTACTAGACACCCTGGGATGAGCCCTTACCATCTCGGGAGGTCCATCGTCACCCCGTTCTTCGTTCGTTACGTGTATCAGAATCCGCACAAGGTGATGGTTCCCGCAGTACTAATGACTTGCTATGACTACCGAGCTGAGGTCTTGTCGCATTCTCGCTCGCCAGTAATCTTTGCCGTTCCCGCGCTATGGCTCTGCACCCAAACCGCCCGCAACCTCTGGTTGCATGCAGTAATGGTGAGCACACTGTTGATCACGTAGGGTTTAACAGAACCCGGTTGAGTAATTGACTGAGCCGTTAAGCATACTGAGGCAGTTAGTGCATAACTGGCCCACTCATTGTTAAGAAGGAGAGGGCAGGCAGTTTAGTAGCTGTGCTTGTTCAAGTTGATTCCGTCCCAGGGGTCCCCCGGACTATCGATCAGATGTCGGGGCACACTGGTTCGCCCAACTTGTTCGATTAAGAATGCCTTTTGACATCGACCAAGTATGGGGACATTGTTTCAACACGACCATGTGTGCGGAACCCATTCAAGCGTGTTGCATCAGCGCGGCCTTCCGCTTTCCCCAGAGAGTGCCAGGATGGTACTGACCCTTCTGTCATTGTCACTGACTCCCTCCAGCGGTTGTGCGTGACACATGGCACTTACTAGACCCGGTTCAACCTACCGCATGGAGCCCACCGTTGGCGAAAATGGCCCACCAGTATCCAACGAGTGCTTATGTCTCTCCGTGATTGGCCACAATGGATGTCCCG`))

	fmt.Print(len(idx.Lookup([]byte(`A`), -1)))
	fmt.Print(` `)
	fmt.Print(len(idx.Lookup([]byte(`C`), -1)))
	fmt.Print(` `)
	fmt.Print(len(idx.Lookup([]byte(`G`), -1)))
	fmt.Print(` `)
	fmt.Println(len(idx.Lookup([]byte(`T`), -1)))
}
